apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-app-deployment
  labels:
    app: guestbook-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook-app
      name: guestbook-app
      tier: frontend
  template:
    metadata:
      labels:
        app: guestbook-app
        name: guestbook-app
        tier: frontend
    spec:
      containers:
      - name: guestbook-app
        image: kubernetes/guestbook:v2
        ports:
        - containerPort: 3000