apiVersion: v1
kind: Service
metadata:
  name: guestbook-app-service
  labels:
    app: guestbook-app-service
spec:
#  type: LoadBalancer
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30100
  selector:
    app: guestbook-app
    name: guestbook-app
    tier: frontend
