apiVersion: v1
kind: Service
metadata:
  name: guestbook-app-service
  labels:
    app: guestbook-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: guestbook-app
    name: guestbook-app
    tier: frontend
