apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-app
      name: redis
      tier: backend
  template:
    metadata:
      labels:
        app: guestbook-app
        name: redis
        tier: backend
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379