apiVersion: v1
kind: Service
metadata:
  name: redis-master # this is the name the guestbook app tries to find the redis
  labels:
    app: redis-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: guestbook-app
    name: redis
    tier: backend
